### ISSUE TITLE
Fire loading event before initiating ajax

### ISSUE THREAD

**Issue by leplatrem** [calvinmetcalf/leaflet-ajax#1]
Just a suggestion. It would allow to show a spin while loading for example (https://github.com/makinacorpus/Leaflet.Spin)

**Comment by calvinmetcalf** [comment]
added this in #2

**Comment by leplatrem** [comment]
Nice, thanks !

I added Leaflet.Spin to plugins page and mentioned your plugin :)

**Comment by calvinmetcalf** [comment]
sweet thanks
