### ISSUE TITLE
Unsafe eval call

### ISSUE THREAD

**Issue by saik0** [calvinmetcalf/leaflet-ajax#14]
Could make `L.Util.JSON` (`window.JSON` OR [json2](https://github.com/douglascrockford/JSON-js/blob/master/json2.js)) and use it in L.Util.ajax

Would get the added benefit of having a legacy JSON.stringify impl

**Comment by calvinmetcalf** [comment]
If you include json2 before leaflet-ajax it will use that in a legacy browser already.

**Comment by saik0** [comment]
IMHO we should either require json2 (or equivalent) as a dep or include it. Doing neither leaves a dangerous blind eval in the codebase.

**Comment by saik0** [comment]
At minimum ensure there are no assignments or invocations

> Security considerations:
> 
> Generally there are security issues with scripting languages.  JSON
>    is a subset of JavaScript, but it is a safe subset that excludes
>    assignment and invocation.
> 
>  A JSON text can be safely passed into JavaScript's eval() function
>    (which compiles and executes a string) if all the characters not
>    enclosed in strings are in the set of characters that form JSON
>    tokens.  This can be quickly determined in JavaScript with two
>    regular expressions and calls to the test and replace methods.
> 
> ```
>  var my_JSON_object = !(/[^,:{}\[\]0-9.\-+Eaeflnr-u \n\r\t]/.test(
>          text.replace(/"(\\.|[^"\\])*"/g, ''))) &&
>      eval('(' + text + ')');
> ```

**Comment by calvinmetcalf** [comment]
This library also does jsonp, you know how jsonp works right?  

The eval will only be called by IE7 and earlier this is not something I'm too concerned about, considering this will only effect same origin requests.

**Comment by calvinmetcalf** [comment]
@saik0 you now have to explicitly pass an option for the eval to happen
