### ISSUE TITLE
setStyle

### ISSUE THREAD

**Issue by bwyss** [calvinmetcalf/leaflet-ajax#18]
I would like to set the style of the layer, I was trying:

var myStyle = {color:'red', fillColor:'orange', radius: 4, apacity: 1.0, fillOpacity: 1.0, weight: 2, clickable: false};

var geojsonLayer = L.geoJson.ajax(myLayer, {style: myStyle});

Does not seem to allow for the style option?
Cheers, Ben

**Comment by calvinmetcalf** [comment]
you're spelling opacity wrong

**Comment by bwyss** [comment]
thanks, but without the typo, I am still get the default leaflet marker

**Comment by calvinmetcalf** [comment]
so under the hood `L.geoJson.ajax(urlToLayer, {style: myStyle});` is the same as `L.geoJson(jsonOfMyLayer, {style: myStyle});` so I'm going to guess that this doesn't work with a vinella geojson layer either, you may have to do

``` javascript
L.geoJson.ajax(urlToLayer, {pointToLayer: function (feature, latlng) {
    return L.circleMarker(latlng, myStyle);
});
```

if that doesn't fix it then a fiddle of your issue would be helpful

**Comment by bwyss** [comment]
worked like a charm, thx, nice plugin by the way!

**Comment by vlasvlasvlas** [comment]
the example has 1 curly braces missing:

```
L.geoJson.ajax(urlToLayer, {pointToLayer: function (feature, latlng) {
    return L.circleMarker(latlng, myStyle);
}
});
```

and that works! :D

txs
