### ISSUE TITLE
[Help] how to could I add a preloader when loading markers from geojson?

### ISSUE THREAD

**Issue by marti1125** [calvinmetcalf/leaflet-ajax#21]
I work with this geojson

http://www.corsproxy.com/earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_week.geojson

the problem is when I have a big data and the app froze while loading markers.

Could you help me ?

**Comment by calvinmetcalf** [comment]
this is a more general leaflet geojson question not specific to this plugin (which is why I'm closing it), but your issue is more then likely related to all the markers your trying to put on the map, if you add the following option

``` javascript
{
    pointToLayer: function (feature, latlng) {
        return L.circleMarker(latlng);
    }
}
```

it'll draw circle makers and it shouldn't be as big a problem.
