### ISSUE TITLE
Error: 'callback' is undefined

### ISSUE THREAD

**Issue by tomchadwin** [calvinmetcalf/leaflet-ajax#23]
I'm getting:

Expected ':'
File: leaflet.ajax.min.js, Line: 1, Column: 12652.

What could cause this?

**Comment by calvinmetcalf** [comment]
try running the leaflet.ajax.js (no min) file so we can see exactly where the error is

**Comment by tomchadwin** [comment]
OK, with the unminified version, I am getting:

'callback' is undefined

The data is coming from Geoserver, so I can give the JSONP wrapper function any name I want. However, if I specify a name, and use callbackParam to specify the same function name, I still get:

'myFunctionName' is undefined

What am I doing wrong? I am using dataType:"jsonp". My knowledge of JS is insufficient to understand the difference between L.GeoJSON.AJAX and L.geoJson.ajax, but I have tried both.

**Comment by calvinmetcalf** [comment]
So with geoserver you have to set callbackParam to the the name of the url
query param that geoserver accepts (which is something weird and un
initiative from what I remember)

**Comment by tomchadwin** [comment]
That's what I'm doing. I am setting the callback function name in my WFS call:

var wfs='http://xx.xxx.com/geoserver/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=xxx:xxxxxx&SRSNAME=EPSG:4326&outputFormat=text%2Fjavascript&format_options=callback%3AmyCallbackName';

I verify that the response to requesting that url starts:

myCallbackName(

I then call leaflet-ajax:

var myLayer=new L.GeoJSON.AJAX(wfs,{dataType:"jsonp", callbackParam:"myCallbackName"});
or:
var myLayer=L.geoJson.ajax(wfs,{dataType:"jsonp", callbackParam:"myCallbackName"});

But this gives me the error:

'myCallbackName' is undefined

What am I doing wrong?

**Comment by calvinmetcalf** [comment]
so in a regular `jsonp` call you put something like `callback=foo` at the end, a few things like mapquest nomanatum have a different param name e.g. `jsonp_callback=foo`  it is the query parameter not the name of the callback that callbackParam sets, you want to set `callbackName` instead.

**Comment by tomchadwin** [comment]
I don't think this will work, as Geoserver seems to allow you to change the callback function name with this variable:

format_options=callback:callbackFunctionName

So the value of the querystring var is not just the callback function name, but a key-value pair.

OK, so if that is not going to work, what is the default callback function name which leaflet-ajax expects? Specifying 'callback' in my WFS call and then omitting the leaflet-ajax callbackParam value gives the original error:

'callback' is undefined

Sorry for so many questions.

**Comment by calvinmetcalf** [comment]
the problem is that every other sever uses a query param for this and geoserver doesn't instead using query param plus a prefix, I believe last time I had to use geoserver with this library I opened a pull request on their github repo (becasue they don't have issue enabled) in order to figure out how to actually post an issue on their jira, eventually I was able to post on their jira where I basically learned that they didn't care that they have a non jsonp thing they called jsonp and in the end I just did

``` html
<script>
var map = L.map// define your map
function myCallback(geojson) {
   L.geoJson(geojson, {/*options*/}).addTo(map);
}
</script>

<script src='http://xx.xxx.com/geoserver/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=xxx:xxxxxx&SRSNAME=EPSG:4326&outputFormat=text%2Fjavascript&format_options=callback%3AmyCallback'></script>
```

**Comment by tomchadwin** [comment]
Yes, but that doesn't help me. That is the approach I was using before, but it means that slower-loading datasets addTo(map) later than faster ones. This means that the order I load layers into Leaflet (and hence wish to be the stacking order of the layers) is muddled up.

That is why I wanted to start using leaflet-ajax, to add the layers before populating them asynchronously.

So, my question still stands. What default jsonp function wrapper name does leaflet-ajax use? I'll just specify that in my Geoserver WFS call with '&format_options=callback:callbackFunctionName'.

**Comment by calvinmetcalf** [comment]
It dynamically creates a function for each layer, you can do what it does
and create an empty layer add it to the map,  and then async populate it
with data

**Comment by tomchadwin** [comment]
We ended up using jQuery's AJAX handling, but since that was overkill (we didn't need jQuery for anything else), I'm looking at this issue again. I might be able to get it to work without leaflet-ajax as per your code above, so I'll close this issue for the moment.

**Comment by mclaeysb** [comment]
I'm also looking to load a GeoServer layer into Leaflet using WFS. I'm using Leaflet-AJAX to load geojson files in my webmaps directory and I'm super happy with it. Is there a way to load WFS layers into Leaflet using Leaflet-AJAX, without having to load jQuerry (which I'm also not using at the moment)? @tomchadwin, did you manage to do it using the code above? If yes, could you explain how? Thanks!

**Comment by calvinmetcalf** [comment]
@mclaeysb this is unrelated could please open a new issue (though if you check the readme more carefully you may find what you want to know)
