### ISSUE TITLE
refilter example

### ISSUE THREAD

**Issue by neogeomat** [calvinmetcalf/leaflet-ajax#24]
Is there an example of using the refilter?

**Comment by calvinmetcalf** [comment]
besides the one in the readme no, but its just a method that takes a function which it filters the layer based on the output discarding any current filter.

**Comment by neogeomat** [comment]
I am having a problem. On refiltering, only one layer is being evaluated ( i have 351). I checked with the source code and added some console.logs

```
refilter: function(a) {
    "function" != typeof a ? (this.filter = !1, this.eachLayer(function(a) {
        console.log("refilter=", a(b.feature));
        a.setStyle({
            stroke: !0,
            clickable: !0
        })
    })) : (this.filter = a, console.log("this=", this), testObject = this, this.eachLayer(function(b) {
        console.log(b);
        // console.log("refilter=", a(b.feature));
        a(b.feature) ? b.setStyle({
            stroke: !0,
            clickable: !0
        }) : b.setStyle({
            stroke: !1,
            clickable: !1
        })
    }))
```

Checking in the console, this._layers has 351 entries but the `console.log(b)` is executed only once.

**Comment by neogeomat** [comment]
I was using marker and setStyle does not work well with marker, it worked with polygons.

**Comment by calvinmetcalf** [comment]
this seems like it might be a problem with [eachLayer](http://leafletjs.com/reference.html#layergroup-eachlayer) what happens when you do 

``` js
layer.EachLayer(function (a){console.log(a)})
```

**Comment by neogeomat** [comment]
It may be because of `setStyle` on Marker. I had this problem in other codes as well. Markers are handled differently.

**Comment by cwlarsen** [comment]
I have the same problem with refilter. 
It works using setOpacity instead of setStyle, but the markers are of course still clickable. 

``` javascript
refilter: function(func) {
        if (typeof func !== 'function') {
            this.filter = false;
            this.eachLayer(function(a) {
                a.setStyle({
                    stroke: true,
                    clickable: true
                });
            });
        }
        else {
            this.filter = func;
            this.eachLayer(function(a) { 
                if (func(a.feature)) {
                    a.setOpacity(1);
                    //a.setStyle({
                    //  stroke: true,
                    //  clickable: true
                    //});
                }
                else {
                    a.setOpacity(0);
                    //a.setStyle({
                    //  stroke: false,
                    //  clickable: false
                    //});
                }
            });
        }
```

**Comment by jsrosas** [comment]
Hey @calvinmetcalf, I called my layer allcalls, if I do allcalls.EachLayer(function (a){console.log(a)}) I get
`Uncaught TypeError: allcalls.EachLayer is not a function`
When I use refilter on allcalls I get error 
`a.setStyle is not a function`

**Comment by calvinmetcalf** [comment]
`eachLayer` not `EachLayer`

**Comment by jsrosas** [comment]
Ok console.log(a) is giving me the array with all my markers and their properties.  But refilter function is still giving me an error of:
`a.setStyle is not a function`

**Comment by calvinmetcalf** [comment]
yeah I really can't speak to why this weird rewritten version of refilter doesn't work, you almost definitly don't want to be setting style in the function which is intended for filtering what is displayed on the map.

**Comment by WilliamWalker** [comment]
@calvinmetcalf I'm having the same trouble.  refilter is working well for polyline features, but not multipolygon features.  I see in the source the filter modifies the stroke and clickable properties of style.  Short of modifying the source, is there anything I can do to make it functional with polygons?

**Comment by WilliamWalker** [comment]
I realized I may be using a newer version of leaflet (1.5.1) than what this plugin was build for.  However, I hacked the refilter method to work for my situation.  There may be a cleaner way to do it, but wanted to share for others who I've seen with similar issues.

```
refilter: function (func) {
    if (typeof func !== 'function') {
      this.filter = false;
      this.eachLayer(function (a) {
        a.setStyle({
          stroke: true,
          clickable: true
        });
        if (a.feature.geometry.type === "MultiPolygon" || a.feature.geometry.type === "Polygon") {
          a.setStyle({ fill: true });
        }
      });
    } else {
      this.filter = func;
      this.eachLayer(function (a) {
        if (func(a.feature)) {
          a.setStyle({
            stroke: true,
            clickable: true
          });
          if (a.feature.geometry.type === "MultiPolygon" || a.feature.geometry.type === "Polygon") {
            a.setStyle({ fill: true });
          }
        } else {
          a.setStyle({
            stroke: false,
            clickable: false
          });
          if (a.feature.geometry.type === "MultiPolygon" || a.feature.geometry.type === "Polygon") {
            a.setStyle({ fill: false });
          }
        }
      });
    }
  }
```
