### ISSUE TITLE
example loading popup only some columns

### ISSUE THREAD

**Issue by vlasvlasvlas** [calvinmetcalf/leaflet-ajax#27]
Hi! this plugin is great,

the only thing i need to show only certain columns on the popup:

```
function popUp(f,l){
    var out = [];
    if (f.properties){
        for(key in f.properties){
            out.push(key+": "+f.properties[key]);
        }
        l.bindPopup(out.join("<br />"));
    }
}
```

i need to only bring 2 specific columns from the geojson:

column names are: 'name_depto' and 'postal'

thanks!!!

**Comment by calvinmetcalf** [comment]
this works identically to the default leaflet feature collection so instead of the loop just grab those specific columns

**Comment by vlasvlasvlas** [comment]
:) thanks!
