### ISSUE TITLE
counties.geojson

### ISSUE THREAD

**Issue by gigster99** [calvinmetcalf/leaflet-ajax#29]
Would you help me by explaining how to modify your `index.html` file to display the map that is rendered when clicking this file:

https://github.com/calvinmetcalf/leaflet-ajax/blob/master/example/counties.geojson

TY.

**Comment by calvinmetcalf** [comment]
fork the repo

![screen shot 2015-05-07 at 7 49 59 am](https://cloud.githubusercontent.com/assets/1128607/7514683/b4ae8856-f48d-11e4-9299-d64e2e7d9ea1.png)

switch the the gh-pages branch

![screen shot 2015-05-07 at 7 50 38 am](https://cloud.githubusercontent.com/assets/1128607/7514698/c7cada70-f48d-11e4-991e-307039e6c46e.png)

go to examples/spin.html

![screen shot 2015-05-07 at 7 51 17 am](https://cloud.githubusercontent.com/assets/1128607/7514709/ee8547c2-f48d-11e4-863c-a40ee7f953a2.png)

click to edit the file

![screen shot 2015-05-07 at 7 53 10 am](https://cloud.githubusercontent.com/assets/1128607/7514738/250f7006-f48e-11e4-9db7-f6c89dfaf8ab.png)

replace this line with 

``` js
var jsonTest = new L.GeoJSON.AJAX("path/to/your/data",{onEachFeature:popUp}).addTo(m);

```

![screen shot 2015-05-07 at 7 53 48 am](https://cloud.githubusercontent.com/assets/1128607/7514742/3cb7db94-f48e-11e4-9cf4-fc1d889da40a.png)

save and then go to http://gigster99.github.io/leaflet-ajax/example/spin.html

**Comment by calvinmetcalf** [comment]
and from what I can tell the counties is already in there so you'd just need to change the line to 

``` js
var jsonTest = new L.GeoJSON.AJAX("counteis.geojson",{onEachFeature:popUp}).addTo(m);
```

**Comment by gigster99** [comment]
Very clear instructions - TY. Will work on this later today.

**Comment by gigster99** [comment]
Works perfectly.
