### ISSUE TITLE
jsonp example

### ISSUE THREAD

**Issue by calvinmetcalf** [calvinmetcalf/leaflet-ajax#3]
the jsonp example is broken because I got rid of that server.

**Comment by stefanocudini** [comment]
hi,

if you want you can use the code js / php of my project:
http://labs.easyblog.it/maps/leaflet-layerjson/

**Comment by calvinmetcalf** [comment]
Thanks, it's more that I had a simple express server that was serving some JSONP which I got rid of because I forgot what I was using it for so all I really need to do is to remember to put the file somewhere that will serve it with padding.  

Also labs.easyblog.it is blocked on my network, FRUSTRATIONS!
