### ISSUE TITLE
Use a custom error handler

### ISSUE THREAD

**Issue by a1an77** [calvinmetcalf/leaflet-ajax#30]
Is there a way to use a custom error handler when the ajax call fails (e.g. server side error)? I would like to have a dedicated function call in that case to notify the user properly instead of just showing nothing on the map with a geoJSON parser error at the JS console.

**Comment by calvinmetcalf** [comment]
If you are using jsonp then no you can't get a custom error when there is a parsing error,  with the xhr you should be able to and I can look into it next week to see if it's a docs issue or a feature I'm lacking

**Comment by calvinmetcalf** [comment]
if there is an error that can be caught (e.g. not a jsonp parsing error) then `data:progress` will be called with an object that has an 'error' method, so setting a listener for

``` js
layer.on('data:progress', function (e) {
    if (e.error) {
        // handle error
    }
});
```

that should handle it
