### ISSUE TITLE
Callback parameters

### ISSUE THREAD

**Issue by PapyPev** [calvinmetcalf/leaflet-ajax#38]
Hello,

I'm a beginner in Javascript, especially in Leaflet, and i have one problem with the L.GeoJSON.AJAX function. In fact, i try to generalize my style based on the layer's name. Now I have this function for my layer : 

``` javascript
/**
 * [Execute asynchronous request and return layerContent]
 * @param  {String} layerUrl  [URL to the layer on the GeoServer]
 * @param  {Object} southWest [SouthWest lat/lon coordinate]
 * @param  {Object} northEast [NorthEast lat/lon coordinate]
 * @param  {String} layerName [Name of the current layer]
 * @return {Object}           [the current layer object -> for the map]
 */
function gs_query(layerUrl, southWest, northEast, layerName){
  return new L.GeoJSON.AJAX(layerUrl
    +"&bbox="+southWest.X+","+southWest.Y+","
    +northEast.X+","+northEast.Y,
    {
      onEachFeature: gs_setPopup, // popup information
      style: gs_setStyle, // for line and polygon
      pointToLayer: gs_setStyle // for point
    }
  );
}
```

And for the <code>gs_style</code> function I received <code>feature</code> and <code>latlng</code> parameters, but i need my layerName from <code>gs_query(...)</code> function. Do you know how can i get it ?

Best Regards,
PapyPev

**Comment by calvinmetcalf** [comment]
define the function in the outer closure which has access to the layerName

closing this as it's a more general leaflet question (the api for L.GeoJSON.AJAX is the same as L.GeoJSON except it takes  a url instead of the data)
