### ISSUE TITLE
characters such as é, à, è, ê, replaced by �

### ISSUE THREAD

**Issue by damiendevienne** [calvinmetcalf/leaflet-ajax#40]
Hello, 
I used leaflet-ajax to load a geojson file that contains names with utf-8 characters such as é, à, è, or ê.
in a leaflet popup or in the console, these characters are rendered as '�'. 
However, if I write down é, à or è myself (without reading it from external geoJSON) they are displayed well. Of course I checked that the encoding was correct within the geojson file. 

Is there a way to specify the encoding in ajax-leaflet and solve this issue ? 
Thanks a lot

**Comment by calvinmetcalf** [comment]
is there a link to the geojson file (or a file that exhibits this issue) publicly available?

**Comment by damiendevienne** [comment]
oups... Starting to answer to you I realized that the problem came from the file itself. I had missed it because emacs (that I use for my code) is able to correclty read ISO-8859-encoded text, which is not the case apparently for other tools on linux... 
I think that the fact that the geojson was created from QGIS on windows and that I use linux may be the problem. 
Thanks
