### ISSUE TITLE
Event on completed rendering?

### ISSUE THREAD

**Issue by 5chdn** [calvinmetcalf/leaflet-ajax#42]
I'm loading custom, ungeneralized GeoJSON tiles and want to find out the time required by leaflet to render each tile. I'm attaching a performance timer to the `data:loaded` event.

```
    geojsonTiles.on('data:loaded', function(e) {
      window.console.log(window.performance.now().toFixed(3) + " geojsonTiles :loaded ");
    });
```

But it seems this event is always fired after the data is loaded, of course, that's by design. After the data is loaded, the geometries get rendered by leaflet. Is there any way to find out when the rendering process is done? I was playing around with global `ajaxComplete` or `ajaxStop` events, but they are not being fired by leaflet-ajax. 

Is there any way to do this correctly? Thanks.

**Comment by calvinmetcalf** [comment]
So you could just use the L.ajax method to load the tiles yourself and then manually add then via L.geojson and then time the render however you'd do it in leaflet... That being said I have no idea how to go about timing render in leaflet.

**Comment by 5chdn** [comment]
Ok, leaflet ajax might be an idea. Thanks for the comment.
