### ISSUE TITLE
leaflet 1.0 rc3 : moveend event occur 'Uncaucht TypeError'

### ISSUE THREAD

**Issue by joongtang** [calvinmetcalf/leaflet-ajax#44]
reproduce the issue
1. Go to url https://jsfiddle.net/joongtang/zr0qxq8g/
2. Zoom out from level 10 to level 8 at once
3. View console tab.
4. Shown error message : "Uncaught TypeError: Cannot read property 'fn' of undefined"

**Comment by calvinmetcalf** [comment]
all we do is fire errors, not anything else special, so  I think this is actually an error in leaflet

**Comment by joongtang** [comment]
Ok~ thanks ^^
