### ISSUE TITLE
Are variables locals ? 

### ISSUE THREAD

**Issue by mmeinert** [calvinmetcalf/leaflet-ajax#46]
I think there is a problem (or a misunderstanding) with variables.
Here is a sample of code which works :

    var categories = {}, category;
    var overlays = {}, categoryName, categoryArray;
    var geoJsonLayer = L.geoJSON(featureCollection, {
      pointToLayer: function(feature, latlng) {
        category = feature.properties.destination;
        if (category == "Museum"){
          iconic = 'noir.svg';
        }
        else {iconic = 'bleu.svg';}
        return L.marker(latlng, {
          icon: L.icon.glyph({
            iconUrl: iconic,
            prefix: '',
            glyph: feature.properties.id
          })
        })
      },
      onEachFeature: function (feature, layer) { 
        if (typeof categories[category] === "undefined") {
        categories[category] = [];
        }
          categories[category].push(layer);
      }
    })
    for (categoryName in categories) {
      categoryArray = categories[categoryName];
      overlays[categoryName] = L.layerGroup(categoryArray).addTo(map);
    }  
    L.control.layers({'Streets': positron.addTo(map)}, overlays).addTo(map);

But this is not working with the same datas of "featureCollection" contained in test.json :

    var categories = {}, category;
    var overlays = {}, categoryName, categoryArray;
    var geoJsonLayer = L.geoJSON.AJAX('test.json", {
      pointToLayer: function(feature, latlng) {
        category = feature.properties.destination;
        if (category == "Museum"){
          iconic = 'noir.svg';
        }
        else {iconic = 'bleu.svg';}
        return L.marker(latlng, {
          icon: L.icon.glyph({
            iconUrl: iconic,
            prefix: '',
            glyph: feature.properties.id
          })
        })
      },
      onEachFeature: function (feature, layer) { 
        if (typeof categories[category] === "undefined") {
        categories[category] = [];
        }
          categories[category].push(layer);
      }
    })
    for (categoryName in categories) {
      categoryArray = categories[categoryName];
      overlays[categoryName] = L.layerGroup(categoryArray).addTo(map);
    }  
    L.control.layers({'Streets': positron.addTo(map)}, overlays).addTo(map);

Since I can see my markers when I move my loop 

    [...]
    onEachFeature: function (feature, layer) { 
        if (typeof categories[category] === "undefined") {
        categories[category] = [];
        }
          categories[category].push(layer);
          for (categoryName in categories) {
              categoryArray = categories[categoryName];
              overlays[categoryName] = L.layerGroup(categoryArray).addTo(map);
          } 
       }
    })

I guess my variables are not visible outside the function.
Note: I have used `console.log(overlays);` in and out the function to be sure there were markers (and control.layers) to place

**Comment by calvinmetcalf** [comment]
ok so the difference is that in the first example you have local data so you are using so every thing is synchronous with the remote data via url its asynchronous because you have to go make a network request to download the data and network requests in JS don't block so onEachFeature runs sometime later after  your for loop runs, you can use an event to make sure you wait until the data is loaded before running the latter stuff i.e.e

```js
geoJsonLayer.on('data:loaded', function () {
  for (categoryName in categories) {
    categoryArray = categories[categoryName];
    overlays[categoryName] = L.layerGroup(categoryArray).addTo(map);
  }  
  L.control.layers({'Streets': positron.addTo(map)}, overlays).addTo(map);
});
```

**Comment by mmeinert** [comment]
That did the trick, thank you for the explanation !
