### ISSUE TITLE
Setting style after load

### ISSUE THREAD

**Issue by danpowell88** [calvinmetcalf/leaflet-ajax#5]
Wheres the best place to set a style after the ajax load is complete

I've tried

``` javascript
var myStyle = {
                    color: "#FFFF00",
                    fillColor: "#FFFF00",
                    weight: 5,
                    opacity: 0.65
                };

var geojsonLayer = new L.GeoJSON.AJAX();

geojsonLayer.on('dataLoadComplete', function() {
                    geojsonLayer.setStyle(myStyle);
                }); 

map.addLayer(geojsonLayer);
geojsonLayer.setStyle(myStyle);
```

and it doens't seem to work, it is being called however.

If I replace the ajax call with a normal call (just loading up a static point) the style is applied correctly.

**Comment by danpowell88** [comment]
Well it looks like it needs to be done on 'layeradd', I'll close this.

**Comment by calvinmetcalf** [comment]
it would probably be easiest to just set the style option like so, it has the same options as a regular geojson layer:

``` JavaScript
var geojsonLayer = L.geoJson.ajax("http:webhost.fake/geojson.json",{style:myStyle}).addTo(m)
```
