### ISSUE TITLE
pointToLayer per feature

### ISSUE THREAD

**Issue by asecondwill** [calvinmetcalf/leaflet-ajax#56]
Hi

I think when using L.geoJson the pointToLayer is called per feature.  But when using leaflet ajax, it only calls that once.  

This prevents setting for eg, an icon according to the feature's properties. 

Is there a way round this?

here is what I'm upto for clarification:
```
var features = new L.GeoJSON.AJAX("/features.json?circuit=555",{
    onEachFeature:onEachFeature,

    style: function (feature) {
			// called per feature:
			console.log(feature.properties.style.fillColor);
      return feature.properties && feature.properties.style;
    },
		
		pointToLayer: function (feature) {
			// only called once
      console.log(feature.properties.shape);
    },
});
```

Thanks for any advice

**Comment by asecondwill** [comment]
Closing, this ticket is a load of rubbish, i was just doing it wrong.

**Comment by StefanBrand** [comment]
How is it done correctly then?
