### ISSUE TITLE
Loading failed on .min version

### ISSUE THREAD

**Issue by dualhammers** [calvinmetcalf/leaflet-ajax#57]
Attempting to develop a map that uses this library. Examples found online include the following line of code

`<script src="https://raw.github.com/calvinmetcalf/leaflet-ajax/master/dist/leaflet.ajax.min.JS"></script>`

But when I attempt to use this link I get the following error

"Loading failed for the <script> with source:" and then the link.

Is there another minified version hosted somewhere?

**Comment by milas991** [comment]
I have the same problem..

**Comment by calvinmetcalf** [comment]
try <script src="https://raw.github.com/calvinmetcalf/leaflet-ajax/master/dist/leaflet.ajax.min.js"></script>

note the lowercase file extention
