### ISSUE TITLE
L.geoJSON.AJAX is not a constructor

### ISSUE THREAD

**Issue by Krulvis** [calvinmetcalf/leaflet-ajax#58]
How do I get this plugin to work when working with npm?
I installed leaflet & leaflet-ajax with npm, and can require leaflet using 'var L = require('leaflet');
however I do not know how to properly include this leaflet-ajax extension with it.

Can anyone point me in the right direction?
Index without using beefy:
`<script src="node_modules/leaflet/dist/leaflet.js"></script>
    <script src="node_modules/leaflet-ajax/dist/leaflet.ajax.js"></script>`

When using beefy I use  var L = require('leaflet');

Along with the accessToken this is the JS code:
```
var map = L.map('map').setView([52.11, 6.16], 7);

L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accesToken}', {
    id: 'mapbox.light',
    accesToken: mapboxAccessToken
}).addTo(map);
```

var geojsonLayer = new L.geoJSON.AJAX("data/townships.json");
geojsonLayer.addTo(map);`

Neither options (with or without beefy) allow me to use the L.geoJSON.AJAX()

**Comment by Krulvis** [comment]
Ok so apparently I need to use: new L.geoJson.ajax() instead of new L.geoJSON.AJAX

**Comment by mhfd28** [comment]
i have issu like thak did this work for you ?
