### ISSUE TITLE
.refresh() doesn't clear the layer

### ISSUE THREAD

**Issue by frafra** [calvinmetcalf/leaflet-ajax#6]
Hi,
I tried your plugin but it doesn't seem to refresh the layer on my page. When I try to do it, I doesn't seem to remove the old one.
Demo: http://prontosoccorso.frafra.eu/test.html
As you can see, every 10 seconds the page gets slower and the shadows became darker.

**Comment by calvinmetcalf** [comment]
yeah I see the problem it's adding an additionally url to the list, try [this version](https://raw.github.com/calvinmetcalf/leaflet-ajax/clear-layers/dist/leaflet.ajax.js)

**Comment by frafra** [comment]
Thanks, you're so fast :)
Actually I get this error in the Firefox console:
TypeError: L.GeoJSON.clearLayer is undefined @ http://prontosoccorso.frafra.eu/leaflet-ajax/dist/leaflet.ajax.js:36

**Comment by calvinmetcalf** [comment]
the down side of being fast, should have been L.GeoJSON.prototype.clearLayers, fixed in the branch

**Comment by frafra** [comment]
Ok, it works now. Thank you ;)

**Comment by calvinmetcalf** [comment]
excelent

**Comment by calvinmetcalf** [comment]
@frafra not sure how it worked for you as I was trying to call the prototype of clearlayers as a function instead of calling prototype.clearlayers

**Comment by frafra** [comment]
I'm sorry: in order to test it I've manually edited the .js file instead of pulling the last revision.

**Comment by calvinmetcalf** [comment]
I figured something along those lines
