### ISSUE TITLE
Can't load JSON file if local

### ISSUE THREAD

**Issue by frafra** [calvinmetcalf/leaflet-ajax#8]
When I use a remote JSON file it works well, but if I run something locally on my browser I get this error:
not well-formed @ file:///home/user/geo.json:1

It seems that it depends from the MIME types. See: http://stackoverflow.com/questions/677902/not-well-formed-error-in-firefox-when-loading-json-file-with-xmlhttprequest

I suppose that there could be some server with wrong or incomplete MIME types and this problem could affect those users too.

leaflet-ajax could force the file loading, regardless of the JSON file MIME type.

**Comment by calvinmetcalf** [comment]
as a rule of thumb you can't use ajax with local files, if you have python 2.x installed you can, from the directory you have your file, run

``` python
python -m SimpleHTTPServer 8888 &
```

or with python 3

``` python
python -m http.server 8888 &
```

**Comment by frafra** [comment]
Thank you very much.

**Comment by sidonaldson** [comment]
I had a similar issue with a fix:  https://github.com/calvinmetcalf/leaflet-ajax/pull/15
