### ISSUE TITLE
No errors, but it doesn't load the json file

### ISSUE THREAD

**Issue by frafra** [calvinmetcalf/leaflet-ajax#9]
Hi,
I copied my test page on another server, and it won't load the json file. The file exists and I get no error from firefox. I also changed the mimetype to application/json, but nothing changed. Actually I've set it as text/plain (as the other server does) but it doesn't work.
Demo http://37.247.55.126/~frafra/index.html

**Comment by calvinmetcalf** [comment]
![points](https://f.cloud.github.com/assets/1128607/305046/e71eb220-964d-11e2-9998-69b5c64ac928.png)
I'd double check my file, also the mime type should be application/json but most browsers (but not all) will accept text/plain.

**Comment by frafra** [comment]
I'm really sorry: I had problem with latlong <-> lotnglat :)
You're right, on Firefox both works (but with text/plain it gives a warning if you open the file directly).

**Comment by calvinmetcalf** [comment]
yeah it's annoying how geojson is x,y while the rest of leaflet is lat,lng
